services:
  spring-frontend:
    build:
      context: frontend
      target: dev
    env_file: ./frontend/.env.dev
    ports:
      - 4200:4200
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - springreact-net
    depends_on:
      - backend

  backend:
    build:
      context: backend
      target: dev
    env_file: ./backend/.env.dev
    ports:
      - 8080:8080
    volumes:
      - ~/.m2:/root/.m2
    networks:
      - springmysql-net
      - springreact-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8-oracle
    env_file: ./mysqldb/.env.dev
    networks:
      - springmysql-net
    volumes:
      - mysqldb-data:/var/lib/mysql
    expose:
      - 3306

networks:
  springreact-net:
  springmysql-net:

volumes:
  mysqldb-data: