services:
  spring-frontend:
    build:
      context: frontend
      target: prod
    env_file: ./frontend/.env.prod
    ports:
      - 4200:80
    networks:
      - springreact-net
    depends_on:
      - backend

  backend:
    build:
      context: backend
      target: prod
    env_file: ./backend/.env.prod
    ports:
      - 8080:8080
    networks:
      - springmysql-net
      - springreact-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8-oracle
    env_file: ./mysqldb/.env.prod
    networks:
      - springmysql-net
    volumes:
      - mysqldb-data:/var/lib/mysql
    expose:
      - 3306

networks:
  springreact-net:
  springmysql-net:

volumes:
  mysqldb-data: