version: "2"

services:

  spring-frontend:
    build:
      context: react-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - springreact-net
  
  spring-backend:
    image: spring-backend
    build:
      context: spring-backend
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/hobbie_backend_db?useSSL=false&serverTimezone=Europe/Paris
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8-oracle

    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=hobbie_backend_db


networks:
  springreact-net:
  springmysql-net: