services:
  spring-frontend:
    build:
      context: react-frontend
      target: dev
    ports:
      - "4200:4200"
    networks:
      - springreact-net
    depends_on:
      - spring-backend
  
  spring-backend:
    build:
      context: spring-backend
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/hobbie_backend_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8-oracle

    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=hobbie_backend_db
    volumes:
      - mysqldb-data:/var/lib/mysql

networks:
  springreact-net:
  springmysql-net:

volumes:
  mysqldb-data: