services:
  spring-frontend:
    build:
      context: react-frontend
      target: dev
    env_file: ./react-frontend/.env.dev
    ports:
      - "4200:4200"
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - springreact-net
    depends_on:
      - spring-backend

  spring-backend:
    build:
      context: spring-backend
    env_file: ./spring-backend/.env.dev
    ports:
      - "8080:8080"
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8-oracle
    env_file: ./mysqldb/.env.dev
    networks:
      - springmysql-net
    volumes:
      - mysqldb-data:/var/lib/mysql

networks:
  springreact-net:
  springmysql-net:

volumes:
  mysqldb-data: